const ABSURD = [
  {frage:"Wie viele Haare hat ein Mensch auf dem Kopf durchschnittlich?", hinweis1:"Es sind deutlich mehr als man denkt", hinweis2:"Zwischen 50.000 und 150.000", antwort:"ca. 100.000 Haare"},
  {frage:"Wie viele Mal niest ein Mensch in seinem Leben durchschnittlich?", hinweis1:"Niesen gehört zum Alltag", hinweis2:"Mehrere hunderttausend Mal", antwort:"ca. 200.000–300.000 Mal"},
  {frage:"Wie viele Würmer leben in einem Quadratmeter Gartenerde?", hinweis1:"Mehr als man ahnt", hinweis2:"Mehrere Hundert", antwort:"ca. 300–400 Würmer"},
  {frage:"Wie lange braucht eine Banane, um sich in der Erde zu zersetzen?", hinweis1:"Früchte zersetzen sich recht schnell", hinweis2:"Wenige Wochen", antwort:"ca. 3–4 Wochen"},
  {frage:"Wie viele Mal faltet man ein Blatt Papier, bis es zur Erde-Mond-Distanz reicht?", hinweis1:"Es klingt unmöglich, aber es ist erschreckend wenig", hinweis2:"Unter 50 Mal", antwort:"42 Mal (theoretisch)"},
  {frage:"Wie lang ist der gesamte Darm eines Erwachsenen (Dünn- und Dickdarm)?", hinweis1:"Viel länger als der Mensch groß ist", hinweis2:"Über 5 Meter", antwort:"ca. 7–8 Meter"},
  {frage:"Wie viele Bienen braucht man, um ein Glas Honig (500 g) zu produzieren?", hinweis1:"Es sind mehr Bienen als man denkt", hinweis2:"Hunderte von Bienen über ihr ganzes Leben", antwort:"ca. 600 Bienen (ihr Lebenswerk)"},
  {frage:"Wie viele Ameisen gibt es auf der Erde schätzungsweise?", hinweis1:"Eine astronomische Zahl", hinweis2:"Über eine Billiarde", antwort:"ca. 20 Billiarden (20.000.000.000.000.000)"},
  {frage:"Wie viele Mal schlägt das menschliche Herz in einem Leben?", hinweis1:"Das Herz schlägt unaufhörlich", hinweis2:"Mehrere Milliarden Mal", antwort:"ca. 2,5 Milliarden Mal"},
  {frage:"Wie viele Liter Speichel produziert ein Mensch täglich?", hinweis1:"Mehr als man denkt", hinweis2:"Über 1 Liter", antwort:"ca. 1–1,5 Liter"},
  {frage:"Wie viele Mozartkugeln wurden 2022 in Salzburg produziert?", hinweis1:"Eine österreichische Spezialität für Touristen", hinweis2:"Über 50 Millionen Stück", antwort:"ca. 90 Millionen Stück"},
  {frage:"Wie lange braucht Licht von der Sonne bis zur Erde?", hinweis1:"Licht ist das Schnellste, was es gibt", hinweis2:"Weniger als 10 Minuten", antwort:"ca. 8 Minuten 20 Sekunden"},
  {frage:"Wie viele Pizzen werden jährlich in Deutschland gegessen?", hinweis1:"Pizza ist das beliebteste Gericht in Deutschland", hinweis2:"Über 1 Milliarde", antwort:"ca. 1,5 Milliarden Pizzen"},
  {frage:"Wie viele Zähne hat ein erwachsener Mensch mit Weisheitszähnen?", hinweis1:"Mehr als Kinder haben", hinweis2:"Zwischen 28 und 32", antwort:"32 Zähne"},
  {frage:"Wie viele Kilometer legt ein Briefträger in Deutschland pro Tag zurück?", hinweis1:"Viel zu Fuß oder mit dem Fahrrad", hinweis2:"Über 10 Kilometer", antwort:"ca. 15–25 km"},
  {frage:"Wie viele Tiere sterben täglich auf deutschen Straßen (Wildunfälle)?", hinweis1:"Besonders Rehe und Wildschweine", hinweis2:"Mehrere tausend", antwort:"ca. 5.000–7.000 Tiere täglich"},
  {frage:"Wie schwer ist der Erdkern schätzungsweise?", hinweis1:"Ein unvorstellbar schweres Objekt", hinweis2:"Mehrere Trilliarden Kilogramm", antwort:"ca. 1,9 × 10²⁴ kg"},
  {frage:"Wie viele Stunden schläft ein Mensch im Laufe seines Lebens?", hinweis1:"Rund ein Drittel des Lebens", hinweis2:"Über 200.000 Stunden", antwort:"ca. 220.000 Stunden"},
  {frage:"Wie viele Liter Blut pumpt das Herz eines Erwachsenen pro Tag durch den Körper?", hinweis1:"Eine erstaunliche Menge", hinweis2:"Über 5.000 Liter", antwort:"ca. 7.000–8.000 Liter"},
  {frage:"Wie viele Schritte macht ein Mensch in seinem ganzen Leben?", hinweis1:"Eine riesige Zahl", hinweis2:"Über 100 Millionen Schritte", antwort:"ca. 150–200 Millionen Schritte"},
  {frage:"Wie viele Arten von Bakterien leben im menschlichen Darm?", hinweis1:"Die Darmmikrobiota ist extrem vielfältig", hinweis2:"Über 100 Arten", antwort:"ca. 300–500 Arten"},
  {frage:"Wie viele Mal hustet ein Mensch durchschnittlich pro Tag (gesund)?", hinweis1:"Husten ist normal und reinigend", hinweis2:"Zwischen 10 und 20 Mal", antwort:"ca. 15 Mal pro Tag"},
  {frage:"Wie viele Tonnen Müll produziert ein Deutscher im Jahr?", hinweis1:"Leider eine erhebliche Menge", hinweis2:"Über 400 Kilogramm", antwort:"ca. 620 kg pro Person"},
  {frage:"Wie lange braucht eine Plastikflasche, bis sie sich in der Natur zersetzt?", hinweis1:"Erschreckend lang", hinweis2:"Mehrere hundert Jahre", antwort:"ca. 450 Jahre"},
  {frage:"Wie viele Eier legt eine Henne in ihrem Leben?", hinweis1:"Hühner sind produktive Legetiere", hinweis2:"Über 500 Eier", antwort:"ca. 600–700 Eier"},
  {frage:"Wie viele Wimpern hat ein Mensch durchschnittlich pro Auge?", hinweis1:"Mehr als man auf den ersten Blick zählen würde", hinweis2:"Zwischen 100 und 200", antwort:"ca. 150–200 Wimpern"},
  {frage:"Wie schwer ist das gesamte Internet schätzungsweise (als physische Datenmenge)?", hinweis1:"Eine bekannte Gedankenübung aus der Physik", hinweis2:"Weniger als 100 Gramm", antwort:"ca. 50 Gramm (als Elektronengewicht)"},
  {frage:"Wie viele Tassen Kaffee werden weltweit täglich getrunken?", hinweis1:"Kaffee ist das beliebteste Getränk der Welt", hinweis2:"Über 1 Milliarde", antwort:"ca. 2 Milliarden Tassen täglich"},
  {frage:"Wie viele Stunden verbringt ein Mensch im Durchschnitt seines Lebens auf der Toilette?", hinweis1:"Mehr als man zugeben möchte", hinweis2:"Über 2.000 Stunden", antwort:"ca. 3.000 Stunden (125 Tage)"},
  {frage:"Wie viele Mücken gibt es schätzungsweise auf der Erde?", hinweis1:"Mehr als genug, um lästig zu sein", hinweis2:"Mehr als 100 Billionen", antwort:"ca. 100–200 Billionen"},
  {frage:"Wie viele Blätter hat eine ausgewachsene Buche?", hinweis1:"Bäume haben erstaunlich viele Blätter", hinweis2:"Über 100.000 Blätter", antwort:"ca. 200.000–300.000 Blätter"},
  {frage:"Wie viele Kerzen würde man brauchen, um die Helligkeit der Sonne zu erreichen?", hinweis1:"Eine unvorstellbare Zahl", hinweis2:"Viele Trilliarden", antwort:"ca. 4 × 10²⁸ Kerzen"},
  {frage:"Wie viele Male könnte man den Äquator mit den Haaren aller Menschen umwickeln?", hinweis1:"Die Haare aller Menschen wären zusammen unglaublich lang", hinweis2:"Über eine Million Mal", antwort:"ca. 4 Millionen Mal"},
  {frage:"Wie viele Würfelzucker-Würfel passen in den Kölner Dom?", hinweis1:"Der Kölner Dom hat ein gigantisches Innenvolumen", hinweis2:"Milliarden von Würfeln", antwort:"ca. 9 Milliarden Würfelzucker"},
  {frage:"Wie lang sind alle Blutgefäße im menschlichen Körper zusammen?", hinweis1:"Das Kreislaufsystem ist enorm ausgedehnt", hinweis2:"Über 80.000 km", antwort:"ca. 100.000 km (2,5× Erdumfang)"},
  {frage:"Wie viele Haarwachstum-Kilometer produziert ein Mensch in seinem Leben?", hinweis1:"Haare wachsen kontinuierlich", hinweis2:"Über 500 km", antwort:"ca. 800–1.000 km"},
  {frage:"Wie viele Tiere sterben pro Jahr durch Plastikmüll im Meer?", hinweis1:"Ein erschreckendes Umweltproblem", hinweis2:"Über 100.000 Tiere", antwort:"ca. 1 Million Meerestiere pro Jahr"},
  {frage:"Wie viele Liter Wasser braucht man, um 1 kg Rindfleisch zu produzieren?", hinweis1:"Fleischproduktion ist wasserintensiv", hinweis2:"Tausende von Litern", antwort:"ca. 15.500 Liter"},
  {frage:"Wie viele Gehirnzellen (Neuronen) hat ein Mensch?", hinweis1:"Das Gehirn ist komplex", hinweis2:"Mehrere Milliarden", antwort:"ca. 86 Milliarden Neuronen"},
  {frage:"Wie viele Bücher werden in Deutschland jährlich veröffentlicht?", hinweis1:"Deutschland ist ein buchstarkes Land", hinweis2:"Über 50.000 Neuerscheinungen", antwort:"ca. 70.000–80.000 Titel pro Jahr"},
  {frage:"Wie viele Kilometer Regenwürmer-Tunnel gibt es im Boden eines Fußballfeldes?", hinweis1:"Regenwürmer sind fleißige Gräber", hinweis2:"Über 1 km", antwort:"ca. 5–10 km Tunnellänge"},
  {frage:"Wie viele Male atmet ein Mensch pro Jahr?", hinweis1:"Atmen passiert automatisch, aber oft", hinweis2:"Mehrere Millionen Atemzüge", antwort:"ca. 8–9 Millionen Atemzüge"},
  {frage:"Wie lang war der längste Bart der Welt (Guinness-Weltrekord)?", hinweis1:"Ein langer Bart ist ein Lebenswerk", hinweis2:"Über 4 Meter", antwort:"5,33 Meter (Sarwan Singh, 2011)"},
  {frage:"Wie viele Bakterien befinden sich auf einer Tastatur?", hinweis1:"Computer sind wahre Keimschleudern", hinweis2:"Mehr als auf einer Toilette", antwort:"ca. 7.500 Bakterien pro cm²"},
  {frage:"Wie viele Tonnen Spinnen fressen alle Spinnen der Welt pro Jahr?", hinweis1:"Spinnen sind enorm wichtige Räuber", hinweis2:"Mehr als die gesamte Menschenmasse", antwort:"ca. 400–800 Millionen Tonnen"},
  {frage:"Wie viele Male öffnet und schließt ein Mensch täglich die Augen (Lidschlag)?", hinweis1:"Blinzeln ist fast unbewusst", hinweis2:"Über 10.000 Mal", antwort:"ca. 15.000–20.000 Mal"},
  {frage:"Wie alt wurde die älteste Katze der Welt?", hinweis1:"Deutlich älter als der normale Katzen-Durchschnitt", hinweis2:"Über 25 Jahre", antwort:"38 Jahre (Creme Puff, USA)"},
  {frage:"Wie viele Haare verliert ein Mensch täglich?", hinweis1:"Haarausfall ist normal", hinweis2:"Zwischen 50 und 150 Haare", antwort:"ca. 100 Haare pro Tag"},
  {frage:"Wie viele Kilogramm Staub sammeln sich pro Jahr in einem durchschnittlichen deutschen Haushalt?", hinweis1:"Hausfrauen und -männer wissen: viel", hinweis2:"Über 5 Kilogramm", antwort:"ca. 8–10 kg Staub pro Jahr"},
  {frage:"Wie lang wäre die Schlange, wenn man alle Würstchen aneinanderreihte, die in Deutschland pro Jahr gegessen werden?", hinweis1:"Deutsche essen viele Würste", hinweis2:"Mehrere Millionen Kilometer", antwort:"ca. 100 Millionen km (Erde-Sonne und zurück)"},
  {frage:"Wie viele Tonnen Mehl werden in Deutschland jährlich verbraucht?", hinweis1:"Brot und Backwaren sind eine deutsche Leidenschaft", hinweis2:"Über 5 Millionen Tonnen", antwort:"ca. 8–9 Millionen Tonnen"},
  {frage:"Wie viele Tropfen Wasser befinden sich in einem Teelöffel?", hinweis1:"Ein Teelöffel fasst 5 ml", hinweis2:"Zwischen 50 und 150 Tropfen", antwort:"ca. 100 Tropfen"},
  {frage:"Wie viel Prozent der DNA teilt der Mensch mit einer Banane?", hinweis1:"DNA ist erstaunlich ähnlich im Tierreich", hinweis2:"Mehr als man denkt – über 30 %", antwort:"ca. 60 % der Gene ähneln sich"},
  {frage:"Wie viele Mal könnte man die Erde mit den Telefonkabeln umwickeln, die Deutschland im Boden hat?", hinweis1:"Deutschlands Telekommunikationsnetz ist riesig", hinweis2:"Mehrere tausend Mal", antwort:"ca. 5.000 Mal"},
  {frage:"Wie viele Kilometer legt eine Honigbiene in ihrem Leben insgesamt zurück?", hinweis1:"Bienen sind fleißige Sammlerinnen", hinweis2:"Über 500 km", antwort:"ca. 800 km"},
  {frage:"Wie viele Sekunden lebt ein Mensch, der 80 Jahre alt wird?", hinweis1:"Eine unfassbar große Zahl", hinweis2:"Über 2 Milliarden Sekunden", antwort:"ca. 2,5 Milliarden Sekunden"},
  {frage:"Wie viele Liter Schweiß produziert ein Mensch pro Tag?", hinweis1:"Je nach Aktivität sehr unterschiedlich", hinweis2:"Bis zu mehreren Litern", antwort:"ca. 0,5–1 Liter (ruhend), bis 10 L bei Sport"},
  {frage:"Wie viele Weingläser Wein trinken die Deutschen pro Jahr insgesamt?", hinweis1:"Wein ist sehr beliebt in Deutschland", hinweis2:"Mehrere Milliarden Gläser", antwort:"ca. 10 Milliarden Gläser (2 Mrd. Liter)"},
  {frage:"Wie viele Kilometer würden alle Spaghetti reichen, die die Deutschen jährlich essen?", hinweis1:"Deutsche lieben Nudeln", hinweis2:"Mehrere Millionen Kilometer", antwort:"ca. 100 Millionen km"},
  {frage:"Wie viele verschiedene Käsesorten gibt es in Frankreich?", hinweis1:"De Gaulle sprach von über 200", hinweis2:"Über 300", antwort:"ca. 350–400 Sorten"},
  {frage:"Wie viele Zellen hat der menschliche Körper?", hinweis1:"Eine astronomische Anzahl", hinweis2:"Mehrere Billionen", antwort:"ca. 37 Billionen Zellen"},
  {frage:"Wie schwer ist ein ausgewachsener Elefant maximal?", hinweis1:"Das schwerste Landtier", hinweis2:"Mehrere Tonnen", antwort:"bis zu 7 Tonnen (afrikanischer Buschelefant)"},
  {frage:"Wie viele Liter Luft atmet ein Mensch täglich ein?", hinweis1:"Luft hat zwar kaum Gewicht, aber viel Volumen", hinweis2:"Über 10.000 Liter", antwort:"ca. 12.000–15.000 Liter"},
  {frage:"Wie viele Schichten hat eine Zwiebel maximal?", hinweis1:"Zwiebelschälen kann tränenreich sein", hinweis2:"Zwischen 10 und 20", antwort:"ca. 10–15 Schichten"},
  {frage:"Wie viele Menschen sterben statistisch gesehen pro Minute weltweit?", hinweis1:"Der Tod ist ein stetiger Begleiter der Menschheit", hinweis2:"Über 50 Menschen pro Minute", antwort:"ca. 110 Menschen pro Minute"},
  {frage:"Wie viele Liter Kaffee trinkt ein Deutscher durchschnittlich pro Jahr?", hinweis1:"Kaffee ist das liebste Heißgetränk der Deutschen", hinweis2:"Über 100 Liter", antwort:"ca. 165 Liter"},
  {frage:"Wie viel Prozent der Insektenarten weltweit sind noch nicht wissenschaftlich beschrieben?", hinweis1:"Die Artenvielfalt der Insekten ist enorm", hinweis2:"Über die Hälfte", antwort:"ca. 80 %"},
  {frage:"Wie viele Kilogramm Honig produziert ein Bienenvolk pro Jahr?", hinweis1:"Honig ist das Ergebnis unzähliger Bienenstunden", hinweis2:"Zwischen 10 und 40 kg", antwort:"ca. 20–30 kg"},
  {frage:"Wie viele Quadratmeter Haut hat ein Erwachsener?", hinweis1:"Die Haut ist das größte Organ", hinweis2:"Zwischen 1 und 2 m²", antwort:"ca. 1,7–2 m²"},
  {frage:"Wie viele Kalorien verbraucht ein Mensch täglich allein durch das Denken?", hinweis1:"Das Gehirn ist ein Energiefresser", hinweis2:"Über 300 Kalorien", antwort:"ca. 400–500 Kalorien"},
  {frage:"Wie viele Bäume werden in Deutschland pro Jahr gepflanzt?", hinweis1:"Aufforstung ist ein wichtiges Umweltziel", hinweis2:"Über 100 Millionen", antwort:"ca. 300–500 Millionen Bäume pro Jahr"},
  {frage:"Wie lang ist der längste Regenwurm, der je gemessen wurde?", hinweis1:"Regenwürmer können erstaunlich groß werden", hinweis2:"Über 50 cm", antwort:"ca. 6,7 Meter (Südafrika)"},
  {frage:"Wie viele Male schlägt ein Kolibri seine Flügel pro Sekunde?", hinweis1:"Kolibris sind die schnellsten Flügelschläger", hinweis2:"Über 50 Mal", antwort:"ca. 50–80 Mal pro Sekunde"},
  {frage:"Wie viele Geburten gibt es weltweit pro Minute?", hinweis1:"Die Weltbevölkerung wächst stetig", hinweis2:"Über 100 Geburten pro Minute", antwort:"ca. 250 Geburten pro Minute"},
  {frage:"Wie viele Knochen hat ein neugeborenes Baby?", hinweis1:"Mehr als ein Erwachsener", hinweis2:"Über 270 Knochen", antwort:"ca. 300–350 Knochen (verschmelzen später zu 206)"},
  {frage:"Wie alt wird eine Gartenschnecke durchschnittlich?", hinweis1:"Schnecken sind langlebiger als gedacht", hinweis2:"Über 3 Jahre", antwort:"ca. 5–7 Jahre"},
  {frage:"Wie viele Liter Wasser verbraucht man beim Duschen (5 Minuten)?", hinweis1:"Duschen ist effizienter als Baden", hinweis2:"Zwischen 30 und 80 Liter", antwort:"ca. 60 Liter"},
  {frage:"Wie viele Kilometer pro Stunde schafft eine Weinbergschnecke?", hinweis1:"Das langsamste Tier in der Sprichwörtlichkeit", hinweis2:"Unter 1 km/h", antwort:"ca. 0,05 km/h"},
  {frage:"Wie viele Mal kann man ein A4-Blatt Papier tatsächlich in der Praxis falten?", hinweis1:"Viel weniger als theoretisch möglich", hinweis2:"Unter 10 Mal", antwort:"ca. 7–8 Mal"},
  {frage:"Wie viel Prozent der Erde ist mit Eis bedeckt?", hinweis1:"Pole und Gletscher zusammengerechnet", hinweis2:"Über 10 %", antwort:"ca. 10 % (Antarktis, Grönland, Gletscher)"},
  {frage:"Wie viele Zähne hat eine Schnecke?", hinweis1:"Mehr als man denkt für ein so kleines Tier", hinweis2:"Über 1.000 Zähne", antwort:"bis zu 25.000 Zahnreihen (Radula)"},
  {frage:"Wie viele Kilogramm Kohlenhydrate isst ein Deutscher durchschnittlich pro Jahr?", hinweis1:"Brot, Nudeln, Kartoffeln – ein Hauptbestandteil", hinweis2:"Über 50 kg", antwort:"ca. 100–120 kg"},
  {frage:"Wie viele Tiere werden jährlich für wissenschaftliche Versuche in Deutschland genutzt?", hinweis1:"Tierversuche sind ein ethisch umstrittenes Thema", hinweis2:"Über 1 Million", antwort:"ca. 2–3 Millionen Tiere"},
  {frage:"Wie lang ist der kürzeste kommerziell angebotene Linienflug der Welt?", hinweis1:"Er verbindet zwei schottische Inseln", hinweis2:"Unter 2 Minuten", antwort:"ca. 90 Sekunden (Westray–Papa Westray, Schottland)"},
  {frage:"Wie viele Kühlschränke besitzt ein Durchschnittsdeutscher in seinem Leben?", hinweis1:"Kühlschränke halten nicht ewig", hinweis2:"Mehr als 5", antwort:"ca. 7–10 Kühlschränke"},
  {frage:"Wie viele Liter Blut hat ein Erwachsener im Körper?", hinweis1:"Weniger als man sich vorstellt", hinweis2:"Zwischen 4 und 7 Liter", antwort:"ca. 5–6 Liter"},
  {frage:"Wie groß ist das Netz einer großen Gartenspinne (Durchmesser)?", hinweis1:"Spinnennetze sind überraschend groß", hinweis2:"Über 30 cm", antwort:"ca. 30–60 cm Durchmesser"},
  {frage:"Wie viele Jahre braucht ein Bambusbaum, bis er blüht?", hinweis1:"Bambus ist eine Sonderling unter den Pflanzen", hinweis2:"Jahrzehnte", antwort:"ca. 60–120 Jahre (je nach Art)"},
  {frage:"Wie viele Milliliter Magensäure produziert ein Mensch täglich?", hinweis1:"Der Magen arbeitet auf Hochtouren", hinweis2:"Über 1 Liter", antwort:"ca. 1,5–3 Liter"},
  {frage:"Wie viel Prozent des menschlichen Körpers besteht aus Wasser?", hinweis1:"Wasser ist unser Hauptbestandteil", hinweis2:"Über 50 %", antwort:"ca. 60–70 %"},
  {frage:"Wie viele Schneeflocken fallen pro Jahr in Deutschland?", hinweis1:"Eine astronomische Zahl an kleinen Kristallen", hinweis2:"Billiarden", antwort:"ca. 10²³ Schneeflocken (100 Trilliarden)"},
  {frage:"Wie viele Liter Bier werden beim Münchner Oktoberfest durchschnittlich getrunken?", hinweis1:"Das weltgrößte Volksfest", hinweis2:"Über 5 Millionen Liter", antwort:"ca. 7,5 Millionen Liter"},
  {frage:"Wie alt wird ein Grönlandhai durchschnittlich?", hinweis1:"Das älteste bekannte Wirbeltier", hinweis2:"Über 200 Jahre", antwort:"ca. 400–500 Jahre"},
  {frage:"Wie viele Tonnen CO₂ produziert ein Mensch in Deutschland im Durchschnitt pro Jahr?", hinweis1:"Der ökologische Fußabdruck ist erheblich", hinweis2:"Über 5 Tonnen", antwort:"ca. 10–11 Tonnen"},
  {frage:"Wie viele Liter Wasser sind in der Erdatmosphäre gespeichert?", hinweis1:"Wolken und Luftfeuchtigkeit zusammen", hinweis2:"Mehr als alle Süßwasserseen der Erde", antwort:"ca. 12.900 km³ (12,9 × 10¹⁵ Liter)"},
  {frage:"Wie viele Mal kann ein Stift schreiben, bevor er leer ist (ca. Meter)?", hinweis1:"Ein Kugelschreiber hält erstaunlich lange", hinweis2:"Über 3 km", antwort:"ca. 5 km Schreiblinie"},
  {frage:"Wie viele Gerüche kann ein Mensch unterscheiden?", hinweis1:"Die Nase ist ein feines Sinnesorgan", hinweis2:"Mehr als 1 Billion", antwort:"ca. 1 Billion (10¹²) verschiedene Gerüche"},
];
